spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.199.77.139:3306/JavaEE?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: JEE
    password: 123
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 3000ms
    timeout: 3000ms
    devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
        exclude: WEB-INF/**
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.backend.shop.pojo

server:
  port: 9090

#shiro-redis:
#  enable: true
#  redis-manager:
#    host: localhost:6379
#
#parking:
#  jwt:
#    # secret key
#    secret: f4e2e52034348f86b67cde581c0f9eb5
#    # token expiration time: 7 days
#    expire: 604800
#    header: Authorization
